### Get available surveys
GET http://localhost:8080/api/surveys

### Get questions
GET http://localhost:8080/api/surveys/3/questions

### Get questions MVC
GET http://localhost:8080/surveys/1/questions

###API: save answer for question
# no-redirect
POST http://localhost:8080/api/answers/1
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=0AA3126CE36E11361F0C66430666001C
X-CSRF-TOKEN:aqKTl462zR6i7cOCkYx-xCOfqD3EmsdmEpOgHwUPT9iXG0yGWpv2pu_S9S6P1PvkqKFKp0CrhQT8o_JLdKSRfGE5Ku-keCjj

{
  "answer": "This is an answer2",
  "surveyId": 2,
  "userId": 5,
  "questionId": {
    "id": 1
  }
}


###Get surveyId and questionId
GET http://localhost:8080/surveys/1/questions
Content-Type: application/json

### Get account page
GET http://localhost:8080/account/1
Cookie: JSESSIONID=2FBFDE3520E1639BE82B35D6A99A94D5

### Get options of question
GET http://localhost:8080/api/optquest/5
Content-Type: application/json
Cookie: JSESSIONID=DBCE5E300402E645B209C5ED1EBCEBB0
X-Csrf-Token: Y8u8TttsY8XFSrsjCoqlTWpAomezUHGk74sVk_wMTKo3pINvV_qNLegPUaHoLIkXOaeRLl9xj1-BaRCJjLJwp8lqdJMCkuAL

### Save answers to choice question
POST http://localhost:8080/api/answers/6

### API: Save User Account
POST http://localhost:8080/api/signup
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=FBBC117D3710BD4B557A4C77F3ABB5A3
X-CSRF-TOKEN: uRrss2llH7Kb5ekbEbqDxbT6vJnRjI_xsDw9LulunM5Qktu23C3ZhltcKIG214sudJe38tfNkaHh6evcgV9ZS4tfqv9g8b7Q

{
  "firstName": "Sofiia",
  "lastName": "Hmyria",
  "email": "gsdhjsd@gmail.com",
  "password": "qwerty"
}

#### API: Save New Answer
POST http://localhost:8080/api/answers/1
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=496CD70699E4F62F50A10A632A1F25E5
X-CSRF-TOKEN: 2x6mixvLJrGhC4K44RTSzNqq6h864qvp2GvpCTkzAFthuSVL4yeVs37yEImMabKBhDnmru_OxycJ1srE6g2PPwtWMzoCjx1y

{
  "range_answer": 6,
  "answerTime": "2024-06-01T16:26:08.404389",
  "questionId": 4,
  "surveyId": 1,
  "userId": 1,
  "answerType": "RANGE"
}

### API: Add Survey
POST http://localhost:8080/api/surveys
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=7AEBDCE7A32653B216899039F34B3D4B
X-CSRF-TOKEN: 6udJCYKlY-XtcoLr7R3ux08wgEts4XlcBkbgD9KV86mSnp3MidYvPeGRUIPAEbDd2TDapS0ErSkN1hpxM3OENufwxpGnpqj5

{
  "surveyName": "Customer Satisfaction Survey",
  "surveyType": "CIRCULAR",
  "questions": [
    {
      "id": 1,
      "questionName": "Rate our service",
      "questionType": "RANGE",
      "surveyId": 4,
      "min": 1,
      "max": 5,
      "step": 1
    },
    {
      "id": 2,
      "questionName": "What did you like the most?",
      "questionType": "OPEN",
      "surveyId": 4
    },
    {
      "id": 3,
      "questionName": "Which features do you use?",
      "questionType": "CHOICE",
      "surveyId": 4,
      "isMultiChoice": true,
      "options": [
        {
          "optionId": 1,
          "optionText": "Feature A"
        },
        {
          "optionId": 2,
          "optionText": "Feature B"
        },
        {
          "optionId": 3,
          "optionText": "Feature C"
        }
      ]
    }
  ]
}

### API: Details test

GET http://localhost:8080/api/surveys/2/details
Content-Type: application/json
Cookie: JSESSIONID=9411BDC3A0A951C98621E1E346CBF223
X-Csrf-Token: g-8YjGve_QR0dIASUbfGq4H7z7zt_GKHmDbGJkgXZKQAbprotot7uVi6m2FZFeMnM5ryn-XO4t7Vy1WqrVL1QisvVcIwXvja

### API: Change survey info

PATCH http://localhost:8080/api/surveys/2
Content-Type: application/json
Cookie: JSESSIONID=6899A113D316C3E8E564051987F7EA57
X-Csrf-Token: 38aRdDzLPJ8JTNpMRRW1bVQyscbvpumnrTaMlbSe4dBq5CUBufCiRQ3_DackKrl7cjiBXzIBnKTekYiKyQe4pYOo2eYL0UNk

{
  "surveyId": 2,
  "surveyName": "HFJjksdfjsd",
  "surveyType": "LINEAR",
  "questions": [
    {
      "id": 6,
      "questionName": "How many hours do you spend on the internet per session?",
      "questionType": "CHOICE",
      "surveyId": 2,
      "options": [
        {
          "optionId": 7,
          "optionText": "1 - 3 hours",
          "question": null,
          "choice": null
        },
        {
          "optionId": 8,
          "optionText": "6 - 7 hours",
          "question": null,
          "choice": null
        },
        {
          "optionId": 9,
          "optionText": "> 7 hours",
          "question": null,
          "choice": null
        }
      ],
      "multiChoice": false
    },
    {
      "id": 7,
      "questionName": "Where do you use the internet? Check all that apply.",
      "questionType": "CHOICE",
      "surveyId": 2,
      "options": [
        {
          "optionId": 10,
          "optionText": "School",
          "question": null,
          "choice": null
        },
        {
          "optionId": 11,
          "optionText": "Library",
          "question": null,
          "choice": null
        },
        {
          "optionId": 12,
          "optionText": "School",
          "question": null,
          "choice": null
        },
        {
          "optionId": 13,
          "optionText": "Phone",
          "question": null,
          "choice": null
        }
      ],
      "multiChoice": true
    },
    {
      "id": 8,
      "questionName": "What sites do you visit most frequently?",
      "questionType": "OPEN",
      "surveyId": 2
    },
    {
      "id": 9,
      "questionName": "What do you like most about the internet?",
      "questionType": "OPEN",
      "surveyId": 2
    },
    {
      "id": 10,
      "questionName": "How would you rate the importance of implementing measures to ensure internet safety and responsible usage in today's digital age?",
      "questionType": "RANGE",
      "surveyId": 2,
      "min": 0,
      "max": 10,
      "step": 1
    }
  ],
  "startDate": null,
  "endDate": null
}

### API: Change questions of one survey (CHOICE)
POST http://localhost:8080/api/surveys/2/questions
Content-Type: application/json
Cookie: JSESSIONID=5EE44D89C3799FEF745391E0B642EDE3
X-Csrf-Token: s3z4qJzahqrQjPoZffvzyP3ER8ElulorHsM1lmM-HZtq9CTfgx7Mzf24tZz9up8pGNbH8M6mavhDi2IGf6cFogUPKKtdkBW7

{
  "questionName": "How many per session?",
  "questionType": "CHOICE",
  "options": [
    {
      "optionText": "School",
      "question": null,
      "choice": null
    },
    {
      "optionText": "Library",
      "question": null,
      "choice": null
    }
  ],
  "multiChoice": false
}

### API: Change questions of one survey (OPEN)
POST http://localhost:8080/api/surveys/2/questions
Content-Type: application/json
Cookie: JSESSIONID=5EE44D89C3799FEF745391E0B642EDE3
X-Csrf-Token: s3z4qJzahqrQjPoZffvzyP3ER8ElulorHsM1lmM-HZtq9CTfgx7Mzf24tZz9up8pGNbH8M6mavhDi2IGf6cFogUPKKtdkBW7

{
  "questionName": "Naahsda?",
  "questionType": "OPEN"
}

### API: Change questions of one survey (RANGE)
PATCH http://localhost:8080/api/surveys/2
Content-Type: application/json
Cookie: JSESSIONID=BB0D73A27C17692623C3196CB9CC0E87
X-Csrf-Token: AEP7sHOGWYcQ0PU7LeH3CM-bK35iEX2Ifpski1RO28tcj5dqZHPDhBayYeU95pQOFMzDOP76BkYEdx-lH_gVvjEt4q0-u6Jd

{
  "surveyName": "Adj sajdal?",
  "surveyType": "CIRCULAR",
  "questions": [
    {
      "id": 1,
      "questionName": "Test",
      "questionType": "OPEN"
    },
    {
      "id": 2,
      "questionName": "TEST",
      "questionType": "OPEN"
    }
  ]
}

