### Get available surveys
GET http://localhost:8080/api/surveys

### Get questions
GET http://localhost:8080/api/surveys/3/questions

### Get questions MVC
GET http://localhost:8080/surveys/1/questions

###API: save answer for question
# no-redirect
POST http://localhost:8080/api/answers/1
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=0AA3126CE36E11361F0C66430666001C
X-CSRF-TOKEN:aqKTl462zR6i7cOCkYx-xCOfqD3EmsdmEpOgHwUPT9iXG0yGWpv2pu_S9S6P1PvkqKFKp0CrhQT8o_JLdKSRfGE5Ku-keCjj

{
  "answer": "This is an answer2",
  "surveyId": 2,
  "userId": 5,
  "questionId": {
    "id": 1
  }
}


###Get surveyId and questionId
GET http://localhost:8080/surveys/1/questions
Content-Type: application/json

### Get account page
GET http://localhost:8080/account/1
Cookie: JSESSIONID=2FBFDE3520E1639BE82B35D6A99A94D5

### Get options of question
GET http://localhost:8080/api/optquest/5
Content-Type: application/json
Cookie: JSESSIONID=DBCE5E300402E645B209C5ED1EBCEBB0
X-Csrf-Token: Y8u8TttsY8XFSrsjCoqlTWpAomezUHGk74sVk_wMTKo3pINvV_qNLegPUaHoLIkXOaeRLl9xj1-BaRCJjLJwp8lqdJMCkuAL

### Save answers to choice question
POST http://localhost:8080/api/answers/6

### API: Save User Account
POST http://localhost:8080/api/signup
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=FBBC117D3710BD4B557A4C77F3ABB5A3
X-CSRF-TOKEN: uRrss2llH7Kb5ekbEbqDxbT6vJnRjI_xsDw9LulunM5Qktu23C3ZhltcKIG214sudJe38tfNkaHh6evcgV9ZS4tfqv9g8b7Q

{
"firstName": "Sofiia",
"lastName":"Hmyria",
"email": "gsdhjsd@gmail.com",
"password": "qwerty"
}

#### API: Save New Answer
POST http://localhost:8080/api/answers/1
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=496CD70699E4F62F50A10A632A1F25E5
X-CSRF-TOKEN: 2x6mixvLJrGhC4K44RTSzNqq6h864qvp2GvpCTkzAFthuSVL4yeVs37yEImMabKBhDnmru_OxycJ1srE6g2PPwtWMzoCjx1y

{
  "range_answer": 6,
  "answerTime": "2024-06-01T16:26:08.404389",
  "questionId": 4,
  "surveyId": 1,
  "userId": 1,
  "answerType": "RANGE"
}

### API: Add Survey
POST http://localhost:8080/api/surveys
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=7AEBDCE7A32653B216899039F34B3D4B
X-CSRF-TOKEN: 6udJCYKlY-XtcoLr7R3ux08wgEts4XlcBkbgD9KV86mSnp3MidYvPeGRUIPAEbDd2TDapS0ErSkN1hpxM3OENufwxpGnpqj5

{
    "surveyName": "Customer Satisfaction Survey",
    "surveyType": "CIRCULAR",
    "questions": [
        {
            "id": 1,
            "questionName": "Rate our service",
            "questionType": "RANGE",
            "surveyId": 4,
            "min": 1,
            "max": 5,
            "step": 1
        },
        {
            "id": 2,
            "questionName": "What did you like the most?",
            "questionType": "OPEN",
            "surveyId": 4
        },
        {
            "id": 3,
            "questionName": "Which features do you use?",
            "questionType": "CHOICE",
            "surveyId": 4,
            "isMultiChoice": true,
            "options": [
                {"optionId": 1, "optionText": "Feature A"},
                {"optionId": 2, "optionText": "Feature B"},
                {"optionId": 3, "optionText": "Feature C"}
            ]
        }
    ]
}

### API: Details test

GET http://localhost:8080/api/surveys/3/details
Content-Type: application/json
Cookie: JSESSIONID=03033768F19FBCD737927F51B7E08AD6
X-Csrf-Token: DnJUcWBZtK7ZrZvW_qU4u7dJfvzkhDrrJaxlBYTstiP4wbqUPkptFFNo0pn0nqLgzIgM2o97U8TXsgPGEchTZOaP00XL-Yus

### API: Change survey info

PATCH http://localhost:8080/api/surveys/2
Content-Type: application/json
Cookie: JSESSIONID=794C3C10BB7955141D1BF5E4E228C746
X-Csrf-Token: DIP9xOtYetvzEKU3Khur2CAocRCnebhCWGwoisqfUGAisSlRbbLJoo1vGO3eJ8BTTjafuhQcXHGRHY5vPVhKuv2nNlcbgEpk

{
  "surveyName": "Customer Satisfaction Survey",
  "surveyType": "LINEAR",
  "questions": [
    {
      "id": 2,
      "questionName": "What did you like the most?",
      "questionType": "OPEN",
      "survey_id": 2
    },
    {
      "id": 1,
      "questionName": "Rate our service",
      "questionType": "RANGE",
      "survey_id": 2,
      "min": 1,
      "max": 5,
      "step": 1
    },
    {
      "id": 3,
      "questionName": "Which features do you use?",
      "questionType": "CHOICE",
      "survey_id": 2,
      "isMultiChoice": true,
      "options": [
        {"optionId": 1, "optionText": "Feature A"},
        {"optionId": 2, "optionText": "Feature B"},
        {"optionId": 3, "optionText": "Feature C"}
      ]
    },
    {
      "id": 4,
      "questionName": "Rate our service",
      "questionType": "RANGE",
      "survey_id": 2,
      "min": 1,
      "max": 5,
      "step": 1
    },
    {
      "id": 5,
      "questionName": "Rate our service",
      "questionType": "RANGE",
      "survey_id": 2,
      "min": 1,
      "max": 5,
      "step": 1
    },
    {
      "id": 6,
      "questionName": "Rate our service",
      "questionType": "RANGE",
      "survey_id": 2,
      "min": 1,
      "max": 5,
      "step": 1
    }
  ]
}