### Get available surveys
GET http://localhost:8080/api/surveys

### Get questions
GET http://localhost:8080/api/surveys/3/questions

### Get questions MVC
GET http://localhost:8080/surveys/1/questions

###API: save answer for question
# no-redirect
POST http://localhost:8080/api/answers/open
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=685BEAC359D214787CB9C262314D9C43
X-CSRF-TOKEN:YgffvHhQIX7FTT_L9HMfKGaZAoS08Gc9MJ_n0cbJtMOmzpHeUTK5ikFpQhzoLAv7zF4rH1f6L72GkVcQBa2D5KCrh_qU9_Dp

{
  "answer": "This is an answer2",
  "surveyId": 7,
  "userId": 5,
  "questionId": {
    "id": 1
  }
}


###Get surveyId and questionId
GET http://localhost:8080/surveys/1/questions
Content-Type: application/json

### Get account page
GET http://localhost:8080/account/1
Cookie: JSESSIONID=2FBFDE3520E1639BE82B35D6A99A94D5

### Get options of question
GET http://localhost:8080/api/optquest/5
Content-Type: application/json
Cookie: JSESSIONID=DBCE5E300402E645B209C5ED1EBCEBB0
X-Csrf-Token: Y8u8TttsY8XFSrsjCoqlTWpAomezUHGk74sVk_wMTKo3pINvV_qNLegPUaHoLIkXOaeRLl9xj1-BaRCJjLJwp8lqdJMCkuAL
